//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medals
    {
        public int Id { get; set; }
        public int medal_type { get; set; }
        public string first_name { get; set; }
        public string family_name { get; set; }
        public string patronymic { get; set; }
    }
}
